### ISSUE TITLE
Incorrect usage of `graphql-js`

### ISSUE THREAD

**Issue by deser** [dangcuuson/graphql-schema-typescript#26]
From https://graphql.org/graphql-js/:
```js
// Run the GraphQL query '{ hello }' and print out the response
graphql(schema, '{ hello }', root).then((response) => {
  console.log(response);
});
```

In src/utils/:

```js
 await graphql({ schema: schema, source: introspectionQuery });
```

**Comment by deser** [comment]
And in source-code:
![image](https://user-images.githubusercontent.com/3010698/63767191-97b01780-c8d5-11e9-8067-23702ebe5560.png)

**Comment by deser** [comment]
Created pull: https://github.com/dangcuuson/graphql-schema-typescript/pull/27

**Comment by dangcuuson** [comment]
Actually graphql-js support both syntax (single arg & multiple args) [via this line](https://github.com/graphql/graphql-js/blob/master/src/graphql.js#L96)

But the es-lint is a nice addition so I'll accep the PR.

Cheers.
