### ISSUE TITLE
`export enum` should be `export const enum` in d.ts files 

### ISSUE THREAD

**Issue by chrisae** [dangcuuson/graphql-schema-typescript#29]
Using a `const enum` gives you the possibility to set

```
"compilerOptions": {
  "preserveConstEnums": true
}
```
in the `tsconfig.json` which will inline used enum values. Otherwise you'll get a runtime error because the enum is not available.

See: [https://github.com/Microsoft/TypeScript/issues/1689](https://github.com/Microsoft/TypeScript/issues/1689)

**Comment by dangcuuson** [comment]
I see,

I thought that string enum always generate a corresponding object so I couldn't use enum in declaration files... shame on me :cry: 

Thanks for the info, will be updated shortly.

**Comment by chrisae** [comment]
Thanks for the quick reply and the update :-)

**Comment by dangcuuson** [comment]
Should be fixed in 1.3.0

I figured out that `const enum` also works with global declaration, so it's a breaking change (as before graphql enum will be generated as string union under global scope)

Cheers!

**Comment by dangcuuson** [comment]
Reopen as I realised that `export const enum` won't generate objects at run time, so any code that uses the enum as run time value will break. e.g: `const allRoles = _.values(Roles)`

I'll just need to check if user is generating code as type declaration or module :smile:
